[package]
authors = ["Angelo L. B. Rodem"]
name = "ocpp_rs"
version = "0.1.9"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/angelorodem/ocpp-rs"
homepage = "https://github.com/angelorodem/ocpp-rs"
description = """
Protocol implementation for Open Charge Point Protocol (OCPP) in Rust.
"""
categories = ["data-structures", "algorithms"]
keywords = ["ocpp", "charger", "oca",  "eletric-vehicle", "ocpp16"]
exclude = ["doc_imgs/", ".*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.26" # No_std
strum_macros = "0.26" # No_std
serde = { version = "1.0", features = ["derive"], default-features = false } # No_std
serde_tuple = {version = "0.5.0", default-features = false} # No_std
serde_json = "1.0" # std
chrono = { version = "0.4", features = ["serde"] } # std
