[package]
authors = ["Angelo L. B. Rodem"]
name = "ocpp_rs"
version = "0.1.4"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/angelorodem/ocpp-rs"
homepage = "https://github.com/angelorodem/ocpp-rs"
description = """
Protocol implementation for Open Charge Point Protocol (OCPP) in Rust.
"""
categories = ["data-structures", "algorithms"]
keywords = ["ocpp", "charger", "oca",  "eletric-vehicle", "ocpp16"]
exclude = ["doc_imgs/", ".*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.26"
strum_macros = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
validator = { version = "0.18.1", features = ["derive"] }
serde_tuple = "0.5.0"
rand = "0.8.5"
