[package]
name = "afl-fuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
afl = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arbitrary = "1.0"

[dependencies.ocpp_rs]
path = ".."