#!/usr/bin/env python3
"""Generate OCPP 2.1 device-model catalog modules from appendix CSV extracts.

Usage:
  python tools/gen_device_model.py
  python tools/gen_device_model.py --check
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_DIR = ROOT / "docs" / "2-1-raw" / "appendices-csv"
OUT_DIR = ROOT / "src" / "v21" / "device_model"


def read_semi(path: Path) -> list[list[str]]:
    text = path.read_text(encoding="utf-8-sig")
    # CSVs use `;` and may have spaces around headers
    rows = []
    for line in text.splitlines():
        if not line.strip():
            continue
        rows.append([c.strip() for c in line.split(";")])
    return rows


def rust_str_list(name: str, items: list[str], doc: str) -> str:
    lines = [f"/// {doc}", f"pub const {name}: &[&str] = &["]
    for it in items:
        esc = it.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{esc}",')
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def gen_components() -> str:
    rows = read_semi(CSV_DIR / "components.csv")
    # header: Component ; Description
    names = []
    for row in rows[1:]:
        if not row or not row[0]:
            continue
        names.append(row[0])
    body = rust_str_list(
        "STANDARD_COMPONENTS",
        names,
        "Standard OCPP 2.1 component names.",
    )
    return f"""//! AUTO-GENERATED by `tools/gen_device_model.py` — do not edit by hand.

{body}
/// Case-insensitive check against [`STANDARD_COMPONENTS`].
#[must_use]
pub fn is_standard_component(name: &str) -> bool {{
    STANDARD_COMPONENTS
        .iter()
        .any(|c| c.eq_ignore_ascii_case(name))
}}
"""


def gen_variables() -> str:
    rows = read_semi(CSV_DIR / "variables.csv")
    # Name ; DataType ; Unit ; Description
    entries = []
    names = []
    for row in rows[1:]:
        if not row or not row[0]:
            continue
        name = row[0]
        dtype = row[1] if len(row) > 1 else ""
        unit = row[2] if len(row) > 2 else ""
        names.append(name)
        entries.append((name, dtype, unit))

    lines = [
        "//! AUTO-GENERATED by `tools/gen_device_model.py` — do not edit by hand.",
        "",
        "/// Standard variable metadata (name, data type, unit).",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct VariableMeta {",
        "    pub name: &'static str,",
        "    pub data_type: &'static str,",
        "    pub unit: &'static str,",
        "}",
        "",
    ]
    lines.append(rust_str_list("STANDARD_VARIABLES", names, "Standard variable names."))
    lines.append("/// Full variable catalog with data type / unit.")
    lines.append("pub const VARIABLE_META: &[VariableMeta] = &[")
    for name, dtype, unit in entries:
        ne = name.replace('"', '\\"')
        de = dtype.replace('"', '\\"')
        ue = unit.replace('"', '\\"')
        lines.append(
            f'    VariableMeta {{ name: "{ne}", data_type: "{de}", unit: "{ue}" }},'
        )
    lines.append("];")
    lines.append("")
    lines.append("/// Case-insensitive check against [`STANDARD_VARIABLES`].")
    lines.append("#[must_use]")
    lines.append("pub fn is_standard_variable(name: &str) -> bool {")
    lines.append("    STANDARD_VARIABLES")
    lines.append("        .iter()")
    lines.append("        .any(|v| v.eq_ignore_ascii_case(name))")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_matrix() -> str:
    rows = read_semi(CSV_DIR / "dm_components_vars.csv")
    # Specific Component;Variable;Instance;Required?;DataType;Unit;Description
    lines = [
        "//! AUTO-GENERATED by `tools/gen_device_model.py` — do not edit by hand.",
        "",
        "/// One row of the component↔variable matrix.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct ComponentVariableRow {",
        "    pub component: &'static str,",
        "    pub variable: &'static str,",
        "    pub instance: &'static str,",
        "    pub required: bool,",
        "    pub data_type: &'static str,",
        "    pub unit: &'static str,",
        "}",
        "",
        "/// Component–variable association matrix.",
        "pub const COMPONENT_VARIABLE_MATRIX: &[ComponentVariableRow] = &[",
    ]
    for row in rows[1:]:
        if len(row) < 4 or not row[0]:
            continue
        comp, var = row[0], row[1]
        instance = row[2] if len(row) > 2 else ""
        req_raw = (row[3] if len(row) > 3 else "").lower()
        required = req_raw in ("yes", "y", "true", "required")
        dtype = row[4] if len(row) > 4 else ""
        unit = row[5] if len(row) > 5 else ""

        def esc(s: str) -> str:
            return s.replace("\\", "\\\\").replace('"', '\\"')

        lines.append(
            "    ComponentVariableRow { "
            f'component: "{esc(comp)}", '
            f'variable: "{esc(var)}", '
            f'instance: "{esc(instance)}", '
            f"required: {str(required).lower()}, "
            f'data_type: "{esc(dtype)}", '
            f'unit: "{esc(unit)}" '
            "},"
        )
    lines.append("];")
    lines.append("")
    lines.append("/// Lookup matrix rows for a component name (case-insensitive).")
    lines.append("pub fn rows_for_component(component: &str) -> impl Iterator<Item = &'static ComponentVariableRow> {")
    lines.append("    COMPONENT_VARIABLE_MATRIX")
    lines.append("        .iter()")
    lines.append("        .filter(move |r| r.component.eq_ignore_ascii_case(component))")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_mod() -> str:
    return """\
//! OCPP 2.1 standardized device-model catalogs (feature `device_model_catalog`).
//!
//! Lookup tables of common component and variable names. Matching is case-insensitive.

pub mod components;
pub mod matrix;
pub mod variables;

pub use components::{is_standard_component, STANDARD_COMPONENTS};
pub use matrix::{rows_for_component, ComponentVariableRow, COMPONENT_VARIABLE_MATRIX};
pub use variables::{is_standard_variable, VariableMeta, STANDARD_VARIABLES, VARIABLE_META};
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.exists() or path.read_text() != content:
            print(f"out of date: {path}", file=sys.stderr)
            return False
        print(f"ok: {path}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not CSV_DIR.is_dir():
        print(f"missing {CSV_DIR}", file=sys.stderr)
        return 1

    ok = True
    ok = write_or_check(OUT_DIR / "mod.rs", gen_mod(), args.check) and ok
    ok = write_or_check(OUT_DIR / "components.rs", gen_components(), args.check) and ok
    ok = write_or_check(OUT_DIR / "variables.rs", gen_variables(), args.check) and ok
    ok = write_or_check(OUT_DIR / "matrix.rs", gen_matrix(), args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
