#!/usr/bin/env python3
"""Generate Value-based JSON Schema constraint validators for ocpp_rs.

Usage:
  python tools/gen_validate.py           # write generated Rust modules
  python tools/gen_validate.py --check   # exit 1 if generated output differs
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_21 = ROOT / "docs" / "2-1-raw" / "schemas"
SCHEMA_16 = ROOT / "docs" / "1-6-raw" / "schemas"
OUT_21 = ROOT / "src" / "v21" / "validate_gen.rs"
OUT_16 = ROOT / "src" / "v16" / "validate_gen.rs"


def snake(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def fn_name(stem: str) -> str:
    return f"validate_{snake(stem)}"


def header() -> str:
    return """\
//! AUTO-GENERATED by `tools/gen_validate.py` — do not edit by hand.
//! Regenerate: `python tools/gen_validate.py`
//! Check: `python tools/gen_validate.py --check`

// Generated stubs often have no constraints; silence noise without weakening hand-written code.
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]
#![allow(dead_code, unused_imports, unused_variables, unused_assignments)]

use crate::validate::{ConstraintViolation, Result as ValidateResult};
use alloc::format;
use alloc::string::String;
use serde_json::Value;

fn check_str_max(path: &str, s: &str, max: usize) -> ValidateResult<()> {
    let len = s.chars().count();
    if len > max {
        return Err(ConstraintViolation::max_length(path, max, len));
    }
    Ok(())
}

fn check_arr_min(path: &str, arr: &[Value], min: usize) -> ValidateResult<()> {
    if arr.len() < min {
        return Err(ConstraintViolation::min_items(path, min, arr.len()));
    }
    Ok(())
}

fn check_arr_max(path: &str, arr: &[Value], max: usize) -> ValidateResult<()> {
    if arr.len() > max {
        return Err(ConstraintViolation::max_items(path, max, arr.len()));
    }
    Ok(())
}

fn check_num_min(path: &str, n: f64, min: f64) -> ValidateResult<()> {
    if n < min {
        return Err(ConstraintViolation::minimum(path, min, n));
    }
    Ok(())
}

fn check_num_max(path: &str, n: f64, max: f64) -> ValidateResult<()> {
    if n > max {
        return Err(ConstraintViolation::maximum(path, max, n));
    }
    Ok(())
}

"""


def collect_refs(defn: dict, out: set[str]) -> None:
    if "$ref" in defn:
        out.add(defn["$ref"].split("/")[-1])
        return
    if isinstance(defn.get("items"), dict):
        collect_refs(defn["items"], out)
    for p in (defn.get("properties") or {}).values():
        collect_refs(p, out)


def property_body_lines(prop: str, pdef: dict, ind: str) -> list[str]:
    """Return check lines for one property (no surrounding `if let Some(v)`)."""
    body: list[str] = []
    if "$ref" in pdef:
        ref = pdef["$ref"].split("/")[-1]
        body.append(f'{ind}let child = format!("{{path}}.{prop}");')
        body.append(f"{ind}{fn_name(ref)}(v, &child)?;")
        return body

    typ = pdef.get("type")
    if isinstance(typ, list):
        typ = next((t for t in typ if t != "null"), typ[0] if typ else None)

    if typ == "string" and "maxLength" in pdef:
        body.append(f"{ind}if let Some(s) = v.as_str() {{")
        body.append(f'{ind}    let child = format!("{{path}}.{prop}");')
        body.append(f"{ind}    check_str_max(&child, s, {pdef['maxLength']})?;")
        body.append(f"{ind}}}")

    if typ in ("integer", "number") or "minimum" in pdef or "maximum" in pdef:
        if "minimum" in pdef or "maximum" in pdef:
            body.append(f"{ind}if let Some(n) = v.as_f64() {{")
            body.append(f'{ind}    let child = format!("{{path}}.{prop}");')
            if "minimum" in pdef:
                body.append(
                    f"{ind}    check_num_min(&child, n, {float(pdef['minimum'])})?;"
                )
            if "maximum" in pdef:
                body.append(
                    f"{ind}    check_num_max(&child, n, {float(pdef['maximum'])})?;"
                )
            body.append(f"{ind}}}")

    if typ == "array":
        items = pdef.get("items") or {}
        has_arr_checks = (
            "minItems" in pdef
            or "maxItems" in pdef
            or "$ref" in items
            or (items.get("type") == "string" and "maxLength" in items)
        )
        if has_arr_checks:
            body.append(f"{ind}if let Some(arr) = v.as_array() {{")
            body.append(f'{ind}    let child = format!("{{path}}.{prop}");')
            if "minItems" in pdef:
                body.append(
                    f"{ind}    check_arr_min(&child, arr, {pdef['minItems']})?;"
                )
            if "maxItems" in pdef:
                body.append(
                    f"{ind}    check_arr_max(&child, arr, {pdef['maxItems']})?;"
                )
            if "$ref" in items:
                ref = items["$ref"].split("/")[-1]
                body.append(f"{ind}    for (i, item) in arr.iter().enumerate() {{")
                body.append(f'{ind}        let ip = format!("{{child}}[{{i}}]");')
                body.append(f"{ind}        {fn_name(ref)}(item, &ip)?;")
                body.append(f"{ind}    }}")
            elif items.get("type") == "string" and "maxLength" in items:
                ml = items["maxLength"]
                body.append(f"{ind}    for (i, item) in arr.iter().enumerate() {{")
                body.append(f"{ind}        if let Some(s) = item.as_str() {{")
                body.append(f'{ind}            let ip = format!("{{child}}[{{i}}]");')
                body.append(f"{ind}            check_str_max(&ip, s, {ml})?;")
                body.append(f"{ind}        }}")
                body.append(f"{ind}    }}")
            body.append(f"{ind}}}")

    return body


def emit_property(lines: list[str], prop: str, pdef: dict, ind: str) -> bool:
    """Emit checks for one property; skip when the schema has no enforceable constraints.

    Returns True if any checks were emitted.
    """
    body = property_body_lines(prop, pdef, ind + "    ")
    if not body:
        return False
    lines.append(f'{ind}if let Some(v) = obj.get("{prop}") {{')
    lines.extend(body)
    lines.append(f"{ind}}}")
    return True


def emit_defn_fn(
    lines: list[str],
    name: str,
    defn: dict,
    schema: dict,
    emitted: set[str],
) -> None:
    fname = fn_name(name)
    if fname in emitted:
        return

    # Emit dependencies first
    refs: set[str] = set()
    collect_refs(defn, refs)
    for r in sorted(refs):
        if r in schema.get("definitions", {}):
            emit_defn_fn(lines, r, schema["definitions"][r], schema, emitted)

    if fname in emitted:
        return
    emitted.add(fname)

    lines.append(f"pub fn {fname}(value: &Value, path: &str) -> ValidateResult<()> {{")
    if defn.get("enum"):
        lines.append("    let _ = (value, path);")
        lines.append("    Ok(())")
        lines.append("}")
        lines.append("")
        return

    if defn.get("type") == "string" and "maxLength" in defn:
        lines.append("    if let Some(s) = value.as_str() {")
        lines.append(f"        check_str_max(path, s, {defn['maxLength']})?;")
        lines.append("    }")
        lines.append("    Ok(())")
        lines.append("}")
        lines.append("")
        return

    if "properties" not in defn and defn.get("type") != "object":
        lines.append("    let _ = (value, path);")
        lines.append("    Ok(())")
        lines.append("}")
        lines.append("")
        return

    prop_lines: list[str] = []
    any_checks = False
    for prop, pdef in (defn.get("properties") or {}).items():
        if emit_property(prop_lines, prop, pdef, "    "):
            any_checks = True

    if not any_checks:
        lines.append("    let _ = (value, path);")
        lines.append("    Ok(())")
        lines.append("}")
        lines.append("")
        return

    lines.append("    let Some(obj) = value.as_object() else {")
    lines.append("        return Ok(());")
    lines.append("    };")
    lines.extend(prop_lines)
    lines.append("    let _ = obj;")
    lines.append("    Ok(())")
    lines.append("}")
    lines.append("")


def schema_root_defn(schema: dict, stem: str) -> dict:
    """Root schema is the message object itself (not under definitions)."""
    return {
        "type": schema.get("type", "object"),
        "properties": schema.get("properties") or {},
        "required": schema.get("required") or [],
    }


def emit_match_arm(lines: list[str], action: str, fn: str) -> None:
    """Emit a match arm, wrapping long lines so `cargo fmt --check` stays clean."""
    call = f"{fn}(payload, action)"
    one_line = f'        "{action}" => {call},'
    if len(one_line) <= 100:
        lines.append(one_line)
        return
    lines.append(f'        "{action}" => {{')
    lines.append(f"            {call}")
    lines.append("        }")


def generate_for_dir(schema_dir: Path, version_label: str) -> str:
    lines: list[str] = [header()]
    # Per-file emission to avoid cross-file def clashes: each schema file gets
    # its own nested module, plus a dispatcher for CALL actions.
    action_dispatch: list[tuple[str, str]] = []  # (action_name, fn)
    response_dispatch: list[tuple[str, str]] = []

    for path in sorted(schema_dir.glob("*.json")):
        stem = path.stem
        schema = json.loads(path.read_text())
        mod = snake(stem)
        lines.append(f"mod {mod} {{")
        # Explicit imports avoid clippy::wildcard_imports (pedantic is warn at crate root).
        lines.append("    use super::{")
        lines.append(
            "        ValidateResult, Value, check_arr_max, check_arr_min, check_num_max,"
        )
        lines.append("        check_num_min, check_str_max, format,")
        lines.append("    };")
        lines.append("")
        body: list[str] = []
        emitted: set[str] = set()
        # definitions
        for dname, ddefn in (schema.get("definitions") or {}).items():
            emit_defn_fn(body, dname, ddefn, schema, emitted)
        # root
        root_name = stem
        emit_defn_fn(body, root_name, schema_root_defn(schema, stem), schema, emitted)
        # indent body
        for bl in body:
            if bl == "":
                lines.append("")
            else:
                lines.append("    " + bl if bl.strip() else "")
        # re-export root validator
        lines.append(f"    pub use self::{fn_name(root_name)} as root;")
        lines.append("}")
        lines.append("")

        if stem.endswith("Request"):
            action = stem[: -len("Request")]
            action_dispatch.append((action, f"{mod}::root"))
        elif stem.endswith("Response"):
            action = stem[: -len("Response")]
            response_dispatch.append((action, f"{mod}::root"))
        elif stem == "NotifyPeriodicEventStream":
            action_dispatch.append((stem, f"{mod}::root"))
        elif version_label.startswith("OCPP 1.6"):
            # 1.6 request schemas omit the "Request" suffix.
            action_dispatch.append((stem, f"{mod}::root"))

    # Dispatchers
    lines.append(
        f"/// Validate a {version_label} CALL/SEND payload object for the given action name."
    )
    lines.append(
        "pub fn validate_action_payload(action: &str, payload: &Value) -> ValidateResult<()> {"
    )
    lines.append("    match action {")
    for action, f in action_dispatch:
        emit_match_arm(lines, action, f)
    lines.append('        _ => Ok(()),')
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append(
        f"/// Validate a {version_label} CALLRESULT payload for the given pending action name."
    )
    lines.append(
        "pub fn validate_response_payload(action: &str, payload: &Value) -> ValidateResult<()> {"
    )
    lines.append("    match action {")
    for action, f in response_dispatch:
        emit_match_arm(lines, action, f)
    lines.append("        _ => Ok(()),")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def rustfmt_source(content: str) -> str:
    """Format generated Rust with rustfmt so codegen --check matches `cargo fmt`."""
    import subprocess

    try:
        proc = subprocess.run(
            ["rustfmt", "--edition", "2024"],
            input=content,
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        return content
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
        return content
    return proc.stdout


def write_or_check(path: Path, content: str, check: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = rustfmt_source(content)
    if check:
        if not path.exists():
            print(f"missing {path}", file=sys.stderr)
            return False
        existing = path.read_text()
        if existing != content:
            print(f"out of date: {path}", file=sys.stderr)
            return False
        print(f"ok: {path}")
        return True
    path.write_text(content)
    print(f"wrote {path} ({len(content)} bytes)")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    ok = True
    if SCHEMA_21.is_dir():
        content = generate_for_dir(SCHEMA_21, "OCPP 2.1")
        ok = write_or_check(OUT_21, content, args.check) and ok
    else:
        print(f"skip v21 schemas (missing {SCHEMA_21})", file=sys.stderr)

    if SCHEMA_16.is_dir():
        content = generate_for_dir(SCHEMA_16, "OCPP 1.6")
        ok = write_or_check(OUT_16, content, args.check) and ok
    else:
        print(f"skip v16 schemas (missing {SCHEMA_16})", file=sys.stderr)

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
