//! AUTO-GENERATED by `tools/gen_validate.py` — do not edit by hand.
//! Regenerate: `python tools/gen_validate.py`
//! Check: `python tools/gen_validate.py --check`

#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unused_imports)]

use crate::validate::{ConstraintViolation, Result as ValidateResult};
use alloc::format;
use alloc::string::String;
use serde_json::Value;

fn check_str_max(path: &str, s: &str, max: usize) -> ValidateResult<()> {
    let len = s.chars().count();
    if len > max {
        return Err(ConstraintViolation::max_length(path, max, len));
    }
    Ok(())
}

fn check_arr_min(path: &str, arr: &[Value], min: usize) -> ValidateResult<()> {
    if arr.len() < min {
        return Err(ConstraintViolation::min_items(path, min, arr.len()));
    }
    Ok(())
}

fn check_arr_max(path: &str, arr: &[Value], max: usize) -> ValidateResult<()> {
    if arr.len() > max {
        return Err(ConstraintViolation::max_items(path, max, arr.len()));
    }
    Ok(())
}

fn check_num_min(path: &str, n: f64, min: f64) -> ValidateResult<()> {
    if n < min {
        return Err(ConstraintViolation::minimum(path, min, n));
    }
    Ok(())
}

fn check_num_max(path: &str, n: f64, max: f64) -> ValidateResult<()> {
    if n > max {
        return Err(ConstraintViolation::maximum(path, max, n));
    }
    Ok(())
}

mod authorize {
    use super::*;

    pub fn validate_authorize(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("idTag") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.idTag");
                check_str_max(&child, s, 20)?;
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_authorize as root;
}

mod authorize_response {
    use super::*;

    pub fn validate_authorize_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("idTagInfo") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_authorize_response as root;
}

mod boot_notification {
    use super::*;

    pub fn validate_boot_notification(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("chargePointVendor") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.chargePointVendor");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("chargePointModel") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.chargePointModel");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("chargePointSerialNumber") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.chargePointSerialNumber");
                check_str_max(&child, s, 25)?;
            }
        }
        if let Some(v) = obj.get("chargeBoxSerialNumber") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.chargeBoxSerialNumber");
                check_str_max(&child, s, 25)?;
            }
        }
        if let Some(v) = obj.get("firmwareVersion") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.firmwareVersion");
                check_str_max(&child, s, 50)?;
            }
        }
        if let Some(v) = obj.get("iccid") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.iccid");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("imsi") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.imsi");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("meterType") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.meterType");
                check_str_max(&child, s, 25)?;
            }
        }
        if let Some(v) = obj.get("meterSerialNumber") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.meterSerialNumber");
                check_str_max(&child, s, 25)?;
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_boot_notification as root;
}

mod boot_notification_response {
    use super::*;

    pub fn validate_boot_notification_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        if let Some(v) = obj.get("currentTime") {}
        if let Some(v) = obj.get("interval") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_boot_notification_response as root;
}

mod cancel_reservation {
    use super::*;

    pub fn validate_cancel_reservation(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("reservationId") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_cancel_reservation as root;
}

mod cancel_reservation_response {
    use super::*;

    pub fn validate_cancel_reservation_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_cancel_reservation_response as root;
}

mod change_availability {
    use super::*;

    pub fn validate_change_availability(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("type") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_change_availability as root;
}

mod change_availability_response {
    use super::*;

    pub fn validate_change_availability_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_change_availability_response as root;
}

mod change_configuration {
    use super::*;

    pub fn validate_change_configuration(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("key") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.key");
                check_str_max(&child, s, 50)?;
            }
        }
        if let Some(v) = obj.get("value") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.value");
                check_str_max(&child, s, 500)?;
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_change_configuration as root;
}

mod change_configuration_response {
    use super::*;

    pub fn validate_change_configuration_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_change_configuration_response as root;
}

mod clear_cache {
    use super::*;

    pub fn validate_clear_cache(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_clear_cache as root;
}

mod clear_cache_response {
    use super::*;

    pub fn validate_clear_cache_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_clear_cache_response as root;
}

mod clear_charging_profile {
    use super::*;

    pub fn validate_clear_charging_profile(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("id") {}
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("chargingProfilePurpose") {}
        if let Some(v) = obj.get("stackLevel") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_clear_charging_profile as root;
}

mod clear_charging_profile_response {
    use super::*;

    pub fn validate_clear_charging_profile_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_clear_charging_profile_response as root;
}

mod data_transfer {
    use super::*;

    pub fn validate_data_transfer(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("vendorId") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.vendorId");
                check_str_max(&child, s, 255)?;
            }
        }
        if let Some(v) = obj.get("messageId") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.messageId");
                check_str_max(&child, s, 50)?;
            }
        }
        if let Some(v) = obj.get("data") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_data_transfer as root;
}

mod data_transfer_response {
    use super::*;

    pub fn validate_data_transfer_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        if let Some(v) = obj.get("data") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_data_transfer_response as root;
}

mod diagnostics_status_notification {
    use super::*;

    pub fn validate_diagnostics_status_notification(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_diagnostics_status_notification as root;
}

mod diagnostics_status_notification_response {
    use super::*;

    pub fn validate_diagnostics_status_notification_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_diagnostics_status_notification_response as root;
}

mod firmware_status_notification {
    use super::*;

    pub fn validate_firmware_status_notification(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_firmware_status_notification as root;
}

mod firmware_status_notification_response {
    use super::*;

    pub fn validate_firmware_status_notification_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_firmware_status_notification_response as root;
}

mod get_composite_schedule {
    use super::*;

    pub fn validate_get_composite_schedule(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("duration") {}
        if let Some(v) = obj.get("chargingRateUnit") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_composite_schedule as root;
}

mod get_composite_schedule_response {
    use super::*;

    pub fn validate_get_composite_schedule_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("scheduleStart") {}
        if let Some(v) = obj.get("chargingSchedule") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_composite_schedule_response as root;
}

mod get_configuration {
    use super::*;

    pub fn validate_get_configuration(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("key") {
            if let Some(arr) = v.as_array() {
                let child = format!("{path}.key");
                for (i, item) in arr.iter().enumerate() {
                    if let Some(s) = item.as_str() {
                        let ip = format!("{child}[{i}]");
                        check_str_max(&ip, s, 50)?;
                    }
                }
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_configuration as root;
}

mod get_configuration_response {
    use super::*;

    pub fn validate_get_configuration_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("configurationKey") {
            if let Some(arr) = v.as_array() {
                let child = format!("{path}.configurationKey");
            }
        }
        if let Some(v) = obj.get("unknownKey") {
            if let Some(arr) = v.as_array() {
                let child = format!("{path}.unknownKey");
                for (i, item) in arr.iter().enumerate() {
                    if let Some(s) = item.as_str() {
                        let ip = format!("{child}[{i}]");
                        check_str_max(&ip, s, 50)?;
                    }
                }
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_configuration_response as root;
}

mod get_diagnostics {
    use super::*;

    pub fn validate_get_diagnostics(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("location") {}
        if let Some(v) = obj.get("retries") {}
        if let Some(v) = obj.get("retryInterval") {}
        if let Some(v) = obj.get("startTime") {}
        if let Some(v) = obj.get("stopTime") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_diagnostics as root;
}

mod get_diagnostics_response {
    use super::*;

    pub fn validate_get_diagnostics_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("fileName") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.fileName");
                check_str_max(&child, s, 255)?;
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_diagnostics_response as root;
}

mod get_local_list_version {
    use super::*;

    pub fn validate_get_local_list_version(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_local_list_version as root;
}

mod get_local_list_version_response {
    use super::*;

    pub fn validate_get_local_list_version_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("listVersion") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_get_local_list_version_response as root;
}

mod heartbeat {
    use super::*;

    pub fn validate_heartbeat(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_heartbeat as root;
}

mod heartbeat_response {
    use super::*;

    pub fn validate_heartbeat_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("currentTime") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_heartbeat_response as root;
}

mod meter_values {
    use super::*;

    pub fn validate_meter_values(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("transactionId") {}
        if let Some(v) = obj.get("meterValue") {
            if let Some(arr) = v.as_array() {
                let child = format!("{path}.meterValue");
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_meter_values as root;
}

mod meter_values_response {
    use super::*;

    pub fn validate_meter_values_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_meter_values_response as root;
}

mod remote_start_transaction {
    use super::*;

    pub fn validate_remote_start_transaction(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("idTag") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.idTag");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("chargingProfile") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_remote_start_transaction as root;
}

mod remote_start_transaction_response {
    use super::*;

    pub fn validate_remote_start_transaction_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_remote_start_transaction_response as root;
}

mod remote_stop_transaction {
    use super::*;

    pub fn validate_remote_stop_transaction(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("transactionId") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_remote_stop_transaction as root;
}

mod remote_stop_transaction_response {
    use super::*;

    pub fn validate_remote_stop_transaction_response(
        value: &Value,
        path: &str,
    ) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_remote_stop_transaction_response as root;
}

mod reserve_now {
    use super::*;

    pub fn validate_reserve_now(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("expiryDate") {}
        if let Some(v) = obj.get("idTag") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.idTag");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("parentIdTag") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.parentIdTag");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("reservationId") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_reserve_now as root;
}

mod reserve_now_response {
    use super::*;

    pub fn validate_reserve_now_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_reserve_now_response as root;
}

mod reset {
    use super::*;

    pub fn validate_reset(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("type") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_reset as root;
}

mod reset_response {
    use super::*;

    pub fn validate_reset_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_reset_response as root;
}

mod send_local_list {
    use super::*;

    pub fn validate_send_local_list(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("listVersion") {}
        if let Some(v) = obj.get("localAuthorizationList") {
            if let Some(arr) = v.as_array() {
                let child = format!("{path}.localAuthorizationList");
            }
        }
        if let Some(v) = obj.get("updateType") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_send_local_list as root;
}

mod send_local_list_response {
    use super::*;

    pub fn validate_send_local_list_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_send_local_list_response as root;
}

mod set_charging_profile {
    use super::*;

    pub fn validate_set_charging_profile(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("csChargingProfiles") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_set_charging_profile as root;
}

mod set_charging_profile_response {
    use super::*;

    pub fn validate_set_charging_profile_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_set_charging_profile_response as root;
}

mod start_transaction {
    use super::*;

    pub fn validate_start_transaction(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("idTag") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.idTag");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("meterStart") {}
        if let Some(v) = obj.get("reservationId") {}
        if let Some(v) = obj.get("timestamp") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_start_transaction as root;
}

mod start_transaction_response {
    use super::*;

    pub fn validate_start_transaction_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("idTagInfo") {}
        if let Some(v) = obj.get("transactionId") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_start_transaction_response as root;
}

mod status_notification {
    use super::*;

    pub fn validate_status_notification(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        if let Some(v) = obj.get("errorCode") {}
        if let Some(v) = obj.get("info") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.info");
                check_str_max(&child, s, 50)?;
            }
        }
        if let Some(v) = obj.get("status") {}
        if let Some(v) = obj.get("timestamp") {}
        if let Some(v) = obj.get("vendorId") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.vendorId");
                check_str_max(&child, s, 255)?;
            }
        }
        if let Some(v) = obj.get("vendorErrorCode") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.vendorErrorCode");
                check_str_max(&child, s, 50)?;
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_status_notification as root;
}

mod status_notification_response {
    use super::*;

    pub fn validate_status_notification_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_status_notification_response as root;
}

mod stop_transaction {
    use super::*;

    pub fn validate_stop_transaction(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("idTag") {
            if let Some(s) = v.as_str() {
                let child = format!("{path}.idTag");
                check_str_max(&child, s, 20)?;
            }
        }
        if let Some(v) = obj.get("meterStop") {}
        if let Some(v) = obj.get("timestamp") {}
        if let Some(v) = obj.get("transactionId") {}
        if let Some(v) = obj.get("reason") {}
        if let Some(v) = obj.get("transactionData") {
            if let Some(arr) = v.as_array() {
                let child = format!("{path}.transactionData");
            }
        }
        let _ = obj;
        Ok(())
    }

    pub use self::validate_stop_transaction as root;
}

mod stop_transaction_response {
    use super::*;

    pub fn validate_stop_transaction_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("idTagInfo") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_stop_transaction_response as root;
}

mod trigger_message {
    use super::*;

    pub fn validate_trigger_message(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("requestedMessage") {}
        if let Some(v) = obj.get("connectorId") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_trigger_message as root;
}

mod trigger_message_response {
    use super::*;

    pub fn validate_trigger_message_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_trigger_message_response as root;
}

mod unlock_connector {
    use super::*;

    pub fn validate_unlock_connector(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("connectorId") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_unlock_connector as root;
}

mod unlock_connector_response {
    use super::*;

    pub fn validate_unlock_connector_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("status") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_unlock_connector_response as root;
}

mod update_firmware {
    use super::*;

    pub fn validate_update_firmware(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        if let Some(v) = obj.get("location") {}
        if let Some(v) = obj.get("retries") {}
        if let Some(v) = obj.get("retrieveDate") {}
        if let Some(v) = obj.get("retryInterval") {}
        let _ = obj;
        Ok(())
    }

    pub use self::validate_update_firmware as root;
}

mod update_firmware_response {
    use super::*;

    pub fn validate_update_firmware_response(value: &Value, path: &str) -> ValidateResult<()> {
        let Some(obj) = value.as_object() else {
            return Ok(());
        };
        let _ = obj;
        Ok(())
    }

    pub use self::validate_update_firmware_response as root;
}

/// Validate a OCPP 1.6 CALL/SEND payload object for the given action name.
pub fn validate_action_payload(action: &str, payload: &Value) -> ValidateResult<()> {
    match action {
        "Authorize" => authorize::root(payload, action),
        "BootNotification" => boot_notification::root(payload, action),
        "CancelReservation" => cancel_reservation::root(payload, action),
        "ChangeAvailability" => change_availability::root(payload, action),
        "ChangeConfiguration" => change_configuration::root(payload, action),
        "ClearCache" => clear_cache::root(payload, action),
        "ClearChargingProfile" => clear_charging_profile::root(payload, action),
        "DataTransfer" => data_transfer::root(payload, action),
        "DiagnosticsStatusNotification" => diagnostics_status_notification::root(payload, action),
        "FirmwareStatusNotification" => firmware_status_notification::root(payload, action),
        "GetCompositeSchedule" => get_composite_schedule::root(payload, action),
        "GetConfiguration" => get_configuration::root(payload, action),
        "GetDiagnostics" => get_diagnostics::root(payload, action),
        "GetLocalListVersion" => get_local_list_version::root(payload, action),
        "Heartbeat" => heartbeat::root(payload, action),
        "MeterValues" => meter_values::root(payload, action),
        "RemoteStartTransaction" => remote_start_transaction::root(payload, action),
        "RemoteStopTransaction" => remote_stop_transaction::root(payload, action),
        "ReserveNow" => reserve_now::root(payload, action),
        "Reset" => reset::root(payload, action),
        "SendLocalList" => send_local_list::root(payload, action),
        "SetChargingProfile" => set_charging_profile::root(payload, action),
        "StartTransaction" => start_transaction::root(payload, action),
        "StatusNotification" => status_notification::root(payload, action),
        "StopTransaction" => stop_transaction::root(payload, action),
        "TriggerMessage" => trigger_message::root(payload, action),
        "UnlockConnector" => unlock_connector::root(payload, action),
        "UpdateFirmware" => update_firmware::root(payload, action),
        _ => Ok(()),
    }
}

/// Validate a OCPP 1.6 CALLRESULT payload for the given pending action name.
pub fn validate_response_payload(action: &str, payload: &Value) -> ValidateResult<()> {
    match action {
        "Authorize" => authorize_response::root(payload, action),
        "BootNotification" => boot_notification_response::root(payload, action),
        "CancelReservation" => cancel_reservation_response::root(payload, action),
        "ChangeAvailability" => change_availability_response::root(payload, action),
        "ChangeConfiguration" => change_configuration_response::root(payload, action),
        "ClearCache" => clear_cache_response::root(payload, action),
        "ClearChargingProfile" => clear_charging_profile_response::root(payload, action),
        "DataTransfer" => data_transfer_response::root(payload, action),
        "DiagnosticsStatusNotification" => {
            diagnostics_status_notification_response::root(payload, action)
        }
        "FirmwareStatusNotification" => {
            firmware_status_notification_response::root(payload, action)
        }
        "GetCompositeSchedule" => get_composite_schedule_response::root(payload, action),
        "GetConfiguration" => get_configuration_response::root(payload, action),
        "GetDiagnostics" => get_diagnostics_response::root(payload, action),
        "GetLocalListVersion" => get_local_list_version_response::root(payload, action),
        "Heartbeat" => heartbeat_response::root(payload, action),
        "MeterValues" => meter_values_response::root(payload, action),
        "RemoteStartTransaction" => remote_start_transaction_response::root(payload, action),
        "RemoteStopTransaction" => remote_stop_transaction_response::root(payload, action),
        "ReserveNow" => reserve_now_response::root(payload, action),
        "Reset" => reset_response::root(payload, action),
        "SendLocalList" => send_local_list_response::root(payload, action),
        "SetChargingProfile" => set_charging_profile_response::root(payload, action),
        "StartTransaction" => start_transaction_response::root(payload, action),
        "StatusNotification" => status_notification_response::root(payload, action),
        "StopTransaction" => stop_transaction_response::root(payload, action),
        "TriggerMessage" => trigger_message_response::root(payload, action),
        "UnlockConnector" => unlock_connector_response::root(payload, action),
        "UpdateFirmware" => update_firmware_response::root(payload, action),
        _ => Ok(()),
    }
}
