//! `MeasurandEnumType`

crate::lenient_str_enum! {
    pub enum MeasurandEnumType {
        CurrentExport => "Current.Export",
        CurrentExportOffered => "Current.Export.Offered",
        CurrentExportMinimum => "Current.Export.Minimum",
        CurrentImport => "Current.Import",
        CurrentImportOffered => "Current.Import.Offered",
        CurrentImportMinimum => "Current.Import.Minimum",
        CurrentOffered => "Current.Offered",
        DisplayPresentSOC => "Display.PresentSOC",
        DisplayMinimumSOC => "Display.MinimumSOC",
        DisplayTargetSOC => "Display.TargetSOC",
        DisplayMaximumSOC => "Display.MaximumSOC",
        DisplayRemainingTimeToMinimumSOC => "Display.RemainingTimeToMinimumSOC",
        DisplayRemainingTimeToTargetSOC => "Display.RemainingTimeToTargetSOC",
        DisplayRemainingTimeToMaximumSOC => "Display.RemainingTimeToMaximumSOC",
        DisplayChargingComplete => "Display.ChargingComplete",
        DisplayBatteryEnergyCapacity => "Display.BatteryEnergyCapacity",
        DisplayInletHot => "Display.InletHot",
        EnergyActiveExportInterval => "Energy.Active.Export.Interval",
        EnergyActiveExportRegister => "Energy.Active.Export.Register",
        EnergyActiveImportInterval => "Energy.Active.Import.Interval",
        EnergyActiveImportRegister => "Energy.Active.Import.Register",
        EnergyActiveImportCableLoss => "Energy.Active.Import.CableLoss",
        EnergyActiveImportLocalGenerationRegister => "Energy.Active.Import.LocalGeneration.Register",
        EnergyActiveNet => "Energy.Active.Net",
        EnergyActiveSetpointInterval => "Energy.Active.Setpoint.Interval",
        EnergyApparentExport => "Energy.Apparent.Export",
        EnergyApparentImport => "Energy.Apparent.Import",
        EnergyApparentNet => "Energy.Apparent.Net",
        EnergyReactiveExportInterval => "Energy.Reactive.Export.Interval",
        EnergyReactiveExportRegister => "Energy.Reactive.Export.Register",
        EnergyReactiveImportInterval => "Energy.Reactive.Import.Interval",
        EnergyReactiveImportRegister => "Energy.Reactive.Import.Register",
        EnergyReactiveNet => "Energy.Reactive.Net",
        EnergyRequestTarget => "EnergyRequest.Target",
        EnergyRequestMinimum => "EnergyRequest.Minimum",
        EnergyRequestMaximum => "EnergyRequest.Maximum",
        EnergyRequestMinimumV2X => "EnergyRequest.Minimum.V2X",
        EnergyRequestMaximumV2X => "EnergyRequest.Maximum.V2X",
        EnergyRequestBulk => "EnergyRequest.Bulk",
        Frequency,
        PowerActiveExport => "Power.Active.Export",
        PowerActiveImport => "Power.Active.Import",
        PowerActiveSetpoint => "Power.Active.Setpoint",
        PowerActiveResidual => "Power.Active.Residual",
        PowerExportMinimum => "Power.Export.Minimum",
        PowerExportOffered => "Power.Export.Offered",
        PowerFactor => "Power.Factor",
        PowerImportOffered => "Power.Import.Offered",
        PowerImportMinimum => "Power.Import.Minimum",
        PowerOffered => "Power.Offered",
        PowerReactiveExport => "Power.Reactive.Export",
        PowerReactiveImport => "Power.Reactive.Import",
        SoC,
        Voltage,
        VoltageMinimum => "Voltage.Minimum",
        VoltageMaximum => "Voltage.Maximum",
    }
    @unknown Unknown
}
